// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// HttpServer is an autogenerated mock type for the HttpServer type
type HttpServer struct {
	mock.Mock
}

// ServeHTTP provides a mock function with given fields: writer, request
func (_m *HttpServer) ServeHTTP(writer http.ResponseWriter, request *http.Request) {
	_m.Called(writer, request)
}
