// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/kaancfidan/bouncer/models"

// RouteMatcher is an autogenerated mock type for the RouteMatcher type
type RouteMatcher struct {
	mock.Mock
}

// MatchRoutePolicies provides a mock function with given fields: path, method
func (_m *RouteMatcher) MatchRoutePolicies(path string, method string) ([]models.RoutePolicy, error) {
	ret := _m.Called(path, method)

	var r0 []models.RoutePolicy
	if rf, ok := ret.Get(0).(func(string, string) []models.RoutePolicy); ok {
		r0 = rf(path, method)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.RoutePolicy)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(path, method)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
